# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=2048)),
                ('attending', models.NullBooleanField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('guest_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.Invitation'),
        ),
        migrations.AddField(
            model_name='guest',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Meal'),
        ),
    ]
